### ISSUE TITLE
Compilation error 

### ISSUE THREAD

**Issue by Cousken** [brehaut/manticore#44] opened 2017-07-29 18:25 UTC
Hello!

Thanks a lot for your very guiding messages on my previous issue, i've had a lot to do but i should have a little more time soon. Also i've engaged a web developer friend of mine, so he can help me out on the way.

Since i took all the recent changes today i am unable to compile with this following error:

```
stream.js:74
      throw er; // Unhandled stream error in pipe.
      ^
Error: ./build/js/workers/data-access.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./data-access/Party in /home/cousken/git/manticore/build/js/workers
resolve file
  /home/cousken/git/manticore/build/js/workers/data-access/Party doesn't exist
  /home/cousken/git/manticore/build/js/workers/data-access/Party.webpack.js doesn't exist
  /home/cousken/git/manticore/build/js/workers/data-access/Party.web.js doesn't exist
  /home/cousken/git/manticore/build/js/workers/data-access/Party.js doesn't exist
  /home/cousken/git/manticore/build/js/workers/data-access/Party.json doesn't exist
resolve directory
  /home/cousken/git/manticore/build/js/workers/data-access/Party doesn't exist (directory default file)
  /home/cousken/git/manticore/build/js/workers/data-access/Party/package.json doesn't exist (directory description file)
[/home/cousken/git/manticore/build/js/workers/data-access/Party]
[/home/cousken/git/manticore/build/js/workers/data-access/Party.webpack.js]
[/home/cousken/git/manticore/build/js/workers/data-access/Party.web.js]
[/home/cousken/git/manticore/build/js/workers/data-access/Party.js]
[/home/cousken/git/manticore/build/js/workers/data-access/Party.json]
 @ ./build/js/workers/data-access.js 13:16-46
```

To make sure i did a git clean, an the result are the same. Steps are - clean repository - yarn - gulp -> receive error.

**Comment by Cousken** [comment] 2017-07-29 18:30
Oh and if i go back to, say, f046fd2, the error disappears.

**Comment by brehaut** [comment] 2017-07-29 18:54
Get yarn to upgrade everything. I think just 'yarn' should be sufficient. I've landed a pile of build system improvements and upgraded dependencies

**Comment by brehaut** [comment] 2017-07-29 18:57
Oh this is with a clean repo. That's surprising. I'll try to find time to have a look at it

**Comment by Cousken** [comment] 2017-07-29 19:03
It's definitely not urgent :)

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Adam Politanski
Game Programmer & Interaction Designer

**Comment by brehaut** [comment] 2017-07-29 20:08
It's no problem, its Sunday morning here. On the other hand, I'm not able to reproduce it locally. Heres what happens when I check the whole thing out clean:

```fish
andrew@fenix ~/tmp> git clone https://github.com/brehaut/manticore.git
Cloning into 'manticore'...
remote: Counting objects: 2115, done.
remote: Compressing objects: 100% (157/157), done.
remote: Total 2115 (delta 163), reused 204 (delta 111), pack-reused 1840
Receiving objects: 100% (2115/2115), 1.10 MiB | 686.00 KiB/s, done.
Resolving deltas: 100% (1325/1325), done.
Checking connectivity... done.


andrew@fenix ~/tmp> cd manticore/
andrew@fenix ~/t/manticore> yarn
yarn install v0.15.1
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
warning lodash@1.0.2: The engine "rhino" appears to be invalid.
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
success Saved lockfile.
✨  Done in 4.54s.


andrew@fenix ~/t/manticore> gulp
error TS18001: A path in an 'extends' option must be relative or rooted, but 'tsconfig.json' is not.
[07:59:05] Using gulpfile ~/tmp/manticore/gulpfile.js
[07:59:05] Starting 'styles'...
[07:59:05] Starting 'build:contrib'...
[07:59:05] Starting 'build:common'...
[07:59:05] Finished 'build:contrib' after 169 ms
[07:59:05] Finished 'styles' after 271 ms
[07:59:07] Finished 'build:common' after 2.08 s
[07:59:07] Starting 'build:main'...
[07:59:07] Starting 'build:workers'...
[07:59:07] Starting 'build:workers:fallback'...
[07:59:09] Finished 'build:workers:fallback' after 1.84 s
[07:59:09] Finished 'build:workers' after 1.85 s
[07:59:09] Finished 'build:main' after 1.85 s
[07:59:09] Starting 'build'...
[07:59:09] Finished 'build' after 25 μs
[07:59:09] Starting 'dist'...
[07:59:09] Version: webpack 1.15.0
                                               Asset     Size  Chunks             Chunk Names
/Users/andrew/tmp/manticore/static/js/data-access.js  7.03 kB       0  [emitted]  main
[07:59:09] Version: webpack 1.15.0
                                              Asset     Size  Chunks             Chunk Names
/Users/andrew/tmp/manticore/static/js/processing.js  6.62 kB       0  [emitted]  main
[07:59:09] Version: webpack 1.15.0
                                                       Asset     Size  Chunks             Chunk Names
/Users/andrew/tmp/manticore/static/js/processing-fallback.js  6.62 kB       0  [emitted]  main
[07:59:10] Version: webpack 1.15.0
                                        Asset    Size  Chunks             Chunk Names
/Users/andrew/tmp/manticore/static/js/main.js  811 kB       0  [emitted]  main
[07:59:10] Finished 'dist' after 829 ms
[07:59:10] Starting 'manifest'...
[07:59:10] Finished 'manifest' after 20 ms
[07:59:10] Starting 'default'...
[07:59:10] Finished 'default' after 12 μs
andrew@fenix ~/t/manticore> 
```

**Comment by brehaut** [comment] 2017-07-29 21:19
Just a quick note: I've added a couple of pages of developer documentation to the wiki

**Comment by brehaut** [comment] 2017-07-30 02:10
Minor note: I realised that I broke the mocha tests when i did the big rejigger of the project dependancies and build stuff

**Comment by Cousken** [comment] 2017-07-30 08:10
Yes i did notice errors using mocha, but at that point i was not sure if i was doing it right :) I'm going to try and reproduce your steps on my machine and will tell you the exact results.

**Comment by Cousken** [comment] 2017-07-30 08:33
```
cousken@Hal-Ubuntu:~/git$ git clone https://github.com/brehaut/manticore.git
Cloning into 'manticore'...
remote: Counting objects: 2143, done.
remote: Compressing objects: 100% (174/174), done.
remote: Total 2143 (delta 181), reused 219 (delta 119), pack-reused 1840
Receiving objects: 100% (2143/2143), 1.11 MiB | 1.11 MiB/s, done.
Resolving deltas: 100% (1343/1343), done.
Checking connectivity... done.
cousken@Hal-Ubuntu:~/git$ cd manticore/
cousken@Hal-Ubuntu:~/git/manticore$ yarn
yarn install v0.27.5
[1/4] Resolving packages...
[2/4] Fetching packages...
warning fsevents@1.1.2: The platform "linux" is incompatible with this module.
info "fsevents@1.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
Done in 2.79s.
cousken@Hal-Ubuntu:~/git/manticore$ gulp
[22:13:57] Using gulpfile ~/git/manticore/gulpfile.js
[22:13:57] Starting 'styles'...
[22:13:57] Starting 'build:contrib'...
[22:13:57] Starting 'build:common'...
[22:13:57] Finished 'build:contrib' after 193 ms
[22:13:57] Finished 'styles' after 309 ms
[22:13:59] Finished 'build:common' after 1.97 s
[22:13:59] Starting 'build:main'...
[22:13:59] Starting 'build:workers'...
[22:13:59] Starting 'build:workers:fallback'...
[22:14:01] Finished 'build:workers' after 1.7 s
[22:14:01] Finished 'build:workers:fallback' after 1.7 s
[22:14:01] Finished 'build:main' after 1.7 s
[22:14:01] Starting 'build'...
[22:14:01] Finished 'build' after 21 μs
[22:14:01] Starting 'dist'...

internal/streams/legacy.js:59
      throw er; // Unhandled stream error in pipe.
      ^
Error: ./build/js/workers/data-access.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./data-access/Party in /home/cousken/git/manticore/build/js/workers
resolve file
  /home/cousken/git/manticore/build/js/workers/data-access/Party doesn't exist
  /home/cousken/git/manticore/build/js/workers/data-access/Party.webpack.js doesn't exist
  /home/cousken/git/manticore/build/js/workers/data-access/Party.web.js doesn't exist
  /home/cousken/git/manticore/build/js/workers/data-access/Party.js doesn't exist
  /home/cousken/git/manticore/build/js/workers/data-access/Party.json doesn't exist
resolve directory
  /home/cousken/git/manticore/build/js/workers/data-access/Party doesn't exist (directory default file)
  /home/cousken/git/manticore/build/js/workers/data-access/Party/package.json doesn't exist (directory description file)
[/home/cousken/git/manticore/build/js/workers/data-access/Party]
[/home/cousken/git/manticore/build/js/workers/data-access/Party.webpack.js]
[/home/cousken/git/manticore/build/js/workers/data-access/Party.web.js]
[/home/cousken/git/manticore/build/js/workers/data-access/Party.js]
[/home/cousken/git/manticore/build/js/workers/data-access/Party.json]
 @ ./build/js/workers/data-access.js 13:16-46
cousken@Hal-Ubuntu:~/git/manticore$ 
```

Here's the log, issue seems the same after a fresh clone and a git clean. I think it's probably something to do with my setup, i tried updating everything and so far nothing has changed... 

I'm getting some warning buy that's all. 

```
cousken@Hal-Ubuntu:~/git/manticore$ yarn upgrade
yarn upgrade v0.27.5
[1/4] Resolving packages...
warning gulp-manifest > minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
warning gulp > vinyl-fs > glob-stream > minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
warning gulp > vinyl-fs > glob-watcher > gaze > globule > minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
warning gulp > vinyl-fs > glob-watcher > gaze > globule > glob > graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
```

**Comment by brehaut** [comment] 2017-07-30 09:36
From a quick glance it appears that webpack is behaving different in your VM to my environment. But I have no idea why.

Webpack is just used for bundling the compiled scripts together into distributable code. Think of it as the linker. I'll try setting it up in a Linux environment when I get a chance

**Comment by Cousken** [comment] 2017-07-30 09:50
Also interesting to add to that is it still works a couple of commits
earlier.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Adam Politanski
Game Programmer & Interaction Designer

**Comment by brehaut** [comment] 2017-07-30 10:59
Not that interesting; I changed up the build and bundle system after those commits and added webpack.

**Comment by brehaut** [comment] 2017-07-30 20:28
Figured it out: you are on a case sensitive filesystem, and both the environments im building on are case insensitive.

**Closed by brehaut** 2017-07-30 20:28 UTC

**Comment by Cousken** [comment] 2017-07-31 05:19
Ah, good catch, it would have taken me ages to figure out.

If I want to keep you updated on the progress I am making, what would be
the appropriate forum?

**Comment by brehaut** [comment] 2017-07-31 06:13
Feel free to flick me an email (the address is on my website) or via twitter @brehaut 

If you do a fork then you can push your changes to the public GitHub and it will be easier for me to see what you are doing too
